// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NuGetTrends.Data;

namespace NuGetTrends.Data.Migrations
{
    [DbContext(typeof(NuGetTrendsContext))]
    partial class NuGetTrendsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseSerialColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0-rc.1.20451.13");

            modelBuilder.Entity("NuGet.Protocol.Catalog.Models.PackageDependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseSerialColumn();

                    b.Property<string>("DependencyId")
                        .HasColumnType("text")
                        .HasColumnName("dependency_id");

                    b.Property<int?>("PackageDependencyGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("package_dependency_group_id");

                    b.Property<string>("Range")
                        .HasColumnType("text")
                        .HasColumnName("range");

                    b.HasKey("Id")
                        .HasName("pk_package_dependency");

                    b.HasIndex("DependencyId");

                    b.HasIndex("PackageDependencyGroupId")
                        .HasDatabaseName("ix_package_dependency_package_dependency_group_id");

                    b.ToTable("package_dependency");
                });

            modelBuilder.Entity("NuGet.Protocol.Catalog.Models.PackageDependencyGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseSerialColumn();

                    b.Property<int?>("PackageDetailsCatalogLeafId")
                        .HasColumnType("integer")
                        .HasColumnName("package_details_catalog_leaf_id");

                    b.Property<string>("TargetFramework")
                        .HasColumnType("text")
                        .HasColumnName("target_framework");

                    b.HasKey("Id")
                        .HasName("pk_package_dependency_group");

                    b.HasIndex("PackageDetailsCatalogLeafId")
                        .HasDatabaseName("ix_package_dependency_group_package_details_catalog_leaf_id");

                    b.ToTable("package_dependency_group");
                });

            modelBuilder.Entity("NuGet.Protocol.Catalog.Models.PackageDetailsCatalogLeaf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseSerialColumn();

                    b.Property<string>("Authors")
                        .HasColumnType("text")
                        .HasColumnName("authors");

                    b.Property<DateTimeOffset>("CommitTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("commit_timestamp");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsPrerelease")
                        .HasColumnType("boolean")
                        .HasColumnName("is_prerelease");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<DateTimeOffset>("LastEdited")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_edited");

                    b.Property<string>("LicenseUrl")
                        .HasColumnType("text")
                        .HasColumnName("license_url");

                    b.Property<bool?>("Listed")
                        .HasColumnType("boolean")
                        .HasColumnName("listed");

                    b.Property<string>("MinClientVersion")
                        .HasColumnType("text")
                        .HasColumnName("min_client_version");

                    b.Property<string>("PackageHash")
                        .HasColumnType("text")
                        .HasColumnName("package_hash");

                    b.Property<string>("PackageHashAlgorithm")
                        .HasColumnType("text")
                        .HasColumnName("package_hash_algorithm");

                    b.Property<string>("PackageId")
                        .HasColumnType("text")
                        .HasColumnName("package_id");

                    b.Property<long>("PackageSize")
                        .HasColumnType("bigint")
                        .HasColumnName("package_size");

                    b.Property<string>("PackageVersion")
                        .HasColumnType("text")
                        .HasColumnName("package_version");

                    b.Property<string>("ProjectUrl")
                        .HasColumnType("text")
                        .HasColumnName("project_url");

                    b.Property<DateTimeOffset>("Published")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published");

                    b.Property<string>("ReleaseNotes")
                        .HasColumnType("text")
                        .HasColumnName("release_notes");

                    b.Property<bool?>("RequireLicenseAgreement")
                        .HasColumnType("boolean")
                        .HasColumnName("require_license_agreement");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<List<string>>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("VerbatimVersion")
                        .HasColumnType("text")
                        .HasColumnName("verbatim_version");

                    b.HasKey("Id")
                        .HasName("pk_package_details_catalog_leafs");

                    b.HasIndex("PackageId");

                    b.HasIndex("PackageId", "PackageVersion")
                        .IsUnique();

                    b.ToTable("package_details_catalog_leafs");
                });

            modelBuilder.Entity("NuGetTrends.Data.Cursor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Value")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_cursors");

                    b.ToTable("cursors");

                    b.HasData(
                        new
                        {
                            Id = "Catalog",
                            Value = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("NuGetTrends.Data.DailyDownload", b =>
                {
                    b.Property<string>("PackageId")
                        .HasColumnType("text")
                        .HasColumnName("package_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<long?>("DownloadCount")
                        .HasColumnType("bigint")
                        .HasColumnName("download_count");

                    b.HasKey("PackageId", "Date");

                    b.ToTable("daily_downloads");
                });

            modelBuilder.Entity("NuGetTrends.Data.DailyDownloadResult", b =>
                {
                    b.Property<long?>("Count")
                        .HasColumnType("bigint")
                        .HasColumnName("download_count");

                    b.Property<DateTime>("Week")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("week");

                    b.ToTable("DailyDownloadResult");
                });

            modelBuilder.Entity("NuGetTrends.Data.PackageDownload", b =>
                {
                    b.Property<string>("PackageId")
                        .HasColumnType("text")
                        .HasColumnName("package_id");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text")
                        .HasColumnName("icon_url");

                    b.Property<long?>("LatestDownloadCount")
                        .HasColumnType("bigint")
                        .HasColumnName("latest_download_count");

                    b.Property<DateTime>("LatestDownloadCountCheckedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("latest_download_count_checked_utc");

                    b.Property<string>("PackageIdLowered")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package_id_lowered");

                    b.HasKey("PackageId");

                    b.HasIndex("PackageIdLowered")
                        .IsUnique();

                    b.ToTable("package_downloads");
                });

            modelBuilder.Entity("NuGet.Protocol.Catalog.Models.PackageDependency", b =>
                {
                    b.HasOne("NuGet.Protocol.Catalog.Models.PackageDependencyGroup", null)
                        .WithMany("Dependencies")
                        .HasForeignKey("PackageDependencyGroupId")
                        .HasConstraintName("fk_package_dependency_package_dependency_group_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NuGet.Protocol.Catalog.Models.PackageDependencyGroup", b =>
                {
                    b.HasOne("NuGet.Protocol.Catalog.Models.PackageDetailsCatalogLeaf", null)
                        .WithMany("DependencyGroups")
                        .HasForeignKey("PackageDetailsCatalogLeafId")
                        .HasConstraintName("fk_package_dependency_group_package_details_catalog_leafs_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NuGet.Protocol.Catalog.Models.PackageDependencyGroup", b =>
                {
                    b.Navigation("Dependencies");
                });

            modelBuilder.Entity("NuGet.Protocol.Catalog.Models.PackageDetailsCatalogLeaf", b =>
                {
                    b.Navigation("DependencyGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
