# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables:
  buildConfiguration: 'Release'
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

steps:

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.2.107'
  inputs:
    version: 2.2.107

- task: DotNetCoreCLI@1
  displayName: NuGet Restore
  inputs:
    command: restore
    projects: '**/NuGetTrends.Api.csproj'

- task: DotNetCoreCLI@1
  displayName: Build
  inputs:
    projects: '**/NuGetTrends.Api.csproj'
    arguments: '--configuration $(BuildConfiguration)'

# TODO: Add tests

- task: DotNetCoreCLI@1
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/NuGetTrends.Api.csproj'
    arguments: '-c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)'
