variables:
  IS_BUILD_SERVER: true
  platform: x64

trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - /src/NuGetTrends.Spa/*
    - /azure-devops/spa-pipeline.yml
    exclude:
    - README.md
pr:
  branches:
    include:
    - master
  paths:
    include:
    - /src/NuGetTrends.Spa/*
    - /azure-devops/spa-pipeline.yml
    exclude:
    - README.md

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    # mac:
    #   imageName: 'macos-10.13'
    # windows:
    #   imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@8.1.1
    npm install -g yarn
    ng --version
  displayName: 'Install build tools'

- script: yarn install
  displayName: 'Install app packages'
  workingDirectory: src/NuGetTrends.Spa

- script: yarn run lint
  displayName: 'Lint'
  workingDirectory: src/NuGetTrends.Spa

- script: yarn run test-cc
  displayName: 'Run Tests'
  workingDirectory: src/NuGetTrends.Spa

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TESTS-*.xml'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage Results'
  condition: succeeded()
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'src/NuGetTrends.Spa/coverage/cobertura-coverage.xml'

- script: yarn run prod
  displayName: 'Run Production Build'
  condition: succeeded()
  workingDirectory: src/NuGetTrends.Spa
