-- ClickHouse Schema Migration: 2026-01-04-02-fix-trending-snapshot-timing
-- (No-op: schema changes were folded into 2026-01-04-01-trending-packages-snapshot.sql
-- to keep all migrations idempotent and safe to re-run on existing databases.)
--
-- Originally this migration dropped and recreated trending_packages_snapshot to rename
-- columns (computed_week → week, current_week_downloads → week_downloads, etc.) and
-- fix the ORDER BY key. That DROP TABLE is destructive on re-run, so the final schema
-- was moved into migration 01 instead.
